import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";
import Hydration from "@/components/hydration";
import Navbar from "@/components/Navbar";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <Hydration>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <Navbar />

              <div className="pt-[166px]">
                {children}
              </div>

              <Toaster />
            </ThemeProvider>
          </Hydration>
        </body>
      </html>
    </SessionProvider>
  );
}
